services:
  web:
    build: .
    command: gunicorn lost_and_found.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"

volumes:
  media_volume: